### ISSUE TITLE
[BUG] Null Pointer Exception on performTrigger

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/Social-Bot-Framework#21]
1. **Summary** - Calling ``SocialBotManagerService.performTrigger`` will lead to a NullPointer exception on SocialBotManagerService.java:1034 line 
2. **Bug Details** 
   1. **What?** - NullPointerException
   2. **Where?** - This happens on the ``develop`` branch of the Social Bot Framework. The bot is connected via Slack
   3. **When?/How often?** - It occurs every time  a user messages the bot
   4. **How?/Current state** - 
 I cloned the [Mensa Service](https://github.com/rwth-acis/las2peer-Mensa-Service) and created my own branch called  ``chatbotCCA``.  I created a bot using the [Social Bot Framework](https://sbf.tech4comp.dbis.rwth-aachen.de/bot-modeling) on the modeling space called ``mensabot``.  I configured a bot action which should trigger a function called ``getDefaultMenu`` on the path ``http://127.0.0.1:8080/mensa/default``. I deployed the bot to my local instance of the Social Bot Manager Service. The bot is connected to Slack. I wrote a message to the bot, asking it for ``menu``. The intent ``menuDefault`` is correctly recognized which should in theory trigger the mensa service funtion. However this results in a NullPointerException and the mensa service is never called.
```
Bot MensaBot triggered:
[]
null
default
MensaBot    pass actingAgent
botagent is b4a9aded5f657ae757c823c78ccad693d34f913d16330cb6dc1ae98a39c26a9133b54e5cafcfaedc9fb1d170a008f69861e60eedcf08d490060ff7ab3720843e
mensanull ; {"msg":"menu","botName":"b4a9aded5f657ae757c823c78ccad693d34f913d16330cb6dc1ae98a39c26a9133b54e5cafcfaedc9fb1d170a008f69861e60eedcf08d490060ff7ab3720843e","channel":"D01920S699A","intent":"menuDefault","email":null,"contextOn":true} null null My string iss:{"msg":"menu","botName":"b4a9aded5f657ae757c823c78ccad693d34f913d16330cb6dc1ae98a39c26a9133b54e5cafcfaedc9fb1d170a008f69861e60eedcf08d490060ff7ab3720843e","channel":"D01920S699A","intent":"menuDefault","email":null,"contextOn":true}
java.lang.NullPointerException
        at i5.las2peer.services.socialBotManagerService.SocialBotManagerService.performTrigger(SocialBotManagerService.java:1034)
        at i5.las2peer.services.socialBotManagerService.SocialBotManagerService.performIntentTrigger(SocialBotManagerService.java:770)
        at i5.las2peer.services.socialBotManagerService.SocialBotManagerService$BotResource$2.run(SocialBotManagerService.java:644)
        at java.lang.Thread.run(Thread.java:748)
Intent processing finished.
```

**Comment by Aran30** [comment]
Tried the service myself and @Produces(Type) was missing in the getMenuDefault. After adding (and checking with @lakhoune) worked fine. Closing.
