### ISSUE TITLE
[ENH] Adjust height of widgets

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/Social-Bot-Framework#54]
1. **Motivation** - Auto-adjust the height of the widget or make them resizable. On my monitor, I have a lot of free space, but I cannot use it for modeling bots.

**Comment by AlexanderNeumann** [comment]
@lakhoune could we use 

``` css
  resize: both;
  overflow: auto;
```` 
for the canvas iframe and for the whole container? and maybe store the set values? 
Any opinions? @Aran30 ?

**Comment by lakhoune** [comment]
> @lakhoune could we use
> 
> ```css
>   resize: both;
>   overflow: auto;
> ```
> 
> for the canvas iframe and for the whole container? and maybe store the set values? Any opinions? @Aran30 ?

Yes I did the resizing in https://github.com/rwth-acis/Social-Bot-Framework/commit/952983ce957cc2bae04730dd07085c120c4c4814
I will now work on storing the values and setting them on initial load

**Comment by lakhoune** [comment]
current status: the dimensions are stored in the localstorage but for some reason the dimensions are not set properly on first load

**Comment by lakhoune** [comment]
Current implementation spans over the whole screen realestate, so no need for having adjustable sizes
