### ISSUE TITLE
[ENH] Slim version of the debug widget

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/Social-Bot-Framework#55]
1. **Motivation** - Slim version of the debug widget. Some options are not needed and should be changed only in one version of the frontend.
2. **Specification** - Either remove some items or remove the widget completely and only show necessary buttons next to the load and store button? (import/export/delete bot model). The meta-model should be connected to the SBF version. So we do not want an import meta-model function for end-users, if they are using another bot version they should stick to the corresponding SBF Frontend version.

**Comment by lakhoune** [comment]
The way I implemented it for now is that I have added a new widget on syncmeta and then published it under a new version on npm and then pull that new version in SBF and use the new widget.
I think it would be better to add this widget in the SBF repository and then copy it to the syncmeta folder to overwrite the original debug widget directly. 
What do you think @AlexanderNeumann ?

**Comment by lakhoune** [comment]
Also there is a bug with the new widget described [here](https://github.com/rwth-acis/Social-Bot-Framework/issues/56)

**Comment by lakhoune** [comment]
> The way I implemented it for now is that I have added a new widget on syncmeta and then published it under a new version on npm and then pull that new version in SBF and use the new widget. I think it would be better to add this widget in the SBF repository and then copy it to the syncmeta folder to overwrite the original debug widget directly. What do you think @AlexanderNeumann ?

I have now implemented it this way. Funnily enough, this also fixes #56

**Comment by AlexanderNeumann** [comment]
great!
