### ISSUE TITLE
Submitting of mensabot model in SBF fails

### ISSUE THREAD

**Issue by piahalkour** [rwth-acis/Social-Bot-Framework#76]
When subitting the model of the MensaBot in the SocialBotFramework the following Error occurs: 

"There is something wrong with your bot model: Exception during RMI invocation!". 

Space: mensabot

**Comment by lakhoune** [comment]
This message means that the social bot manager is not connected to the las2peer network

**Comment by FBasels** [comment]
The error can also occure if there are some envelope issues at the SBM.  In this case, one workaround is to submit the bot with a new name.
