### ISSUE TITLE
[BUG] Message repeated after pressing enter

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/Social-Bot-Framework#92]
1. **Summary** 
Every time I press enter in an element it gets repeated
2. **Bug Details** 
![enter-bug](https://user-images.githubusercontent.com/10010710/223707247-94f1aca7-05b3-46bd-94a9-070f00053b0b.gif)

**Comment by lakhoune** [comment]
Can confirm that this is an issue in syncmeta. Created [a seperate issue ](https://github.com/rwth-acis/syncmeta/issues/105) for it
