### ISSUE TITLE
[BUG] Error running apt-get when building using Docker

### ISSUE THREAD

**Issue by samuelvkwong** [rwth-acis/Social-Bot-Framework#94]
System: M1 Mac version 12.6
Building the framework using the docker command fails when running the apt-get step
docker build -t rwthacis/sbf-utils .

![image](https://user-images.githubusercontent.com/130673431/236456899-d1c266bb-725c-440d-9858-35fabb7cd82e.png)

The solution would be to edit my repository configuration as suggested here: https://unix.stackexchange.com/questions/743839/apt-get-update-failed-to-fetch-debian-amd64-packages-while-building-dockerfile-f but there is no /etc/apt directory

**Comment by lakhoune** [comment]
Will be fixed in https://github.com/rwth-acis/Social-Bot-Framework/pull/88 , use branch `develop` for now
